### ISSUE TITLE
Compatibility with old PHP versions

### ISSUE THREAD

**Issue by mCIN4R** [TypistTech/wp-admin-tabs#18]
Hi Rufus,

This is a really good package. 

Would you make this compatible with the PHP version 5.3? I guess the package can only work with PHP 7.0 or higher versions.

We will lose a lot of users if you check the usage stats from WordPress, which is located under this url: [https://wordpress.org/about/stats/](https://wordpress.org/about/stats/)

Thank you..

**Comment by tangrufus** [comment]
No plan to support PHP 5.x or 7.0.

I only use [active supported PHP versions](https://secure.php.net/supported-versions.php) on my clients' sites.
